export const COPY = {
  en: {
    tagline: "A morning paper for India, with the world kept on the same page.",
    search: "City, topic, or name",
    searchGo: "Search",
    all: "All of it",
    india: "India",
    world: "World",
    region: "Region",
    topic: "Topic",
    place: "Place",
    everywhere: "Everywhere",
    allTopics: "Every topic",
    allPlaces: "Every place",
    read: "Read the piece",
    close: "Close",
    prev: "Previous",
    next: "Next",
    clear: "Clear this",
    matchOne: "story in this cut of the paper",
    matchMany: "stories in this cut of the paper",
    nothingKicker: "Empty column",
    nothingTitle: "Nothing filed under that heading.",
    nothingBody: "Try another city, or clear the filters. The rest of the paper is still here.",
    onlyPiece: "That's the only piece in this cut of the paper.",
    worldKicker: "Abroad",
    worldTitle: "The biggest stories beyond India",
    worldNote: "Gaza, Tehran’s supply lines, Beijing, a promise made in Rome, and a renamed machine.",
    indiaKicker: "Home",
    indiaTitle: "The rest of the country this morning",
    indiaNote: "The court, Thane, gold in Nagoya, a tired market, and the last of the rain.",
    resultsKicker: "Your cut",
    resultsTitle: "Also under this heading",
    resultsNote: "The piece above is the one we would put on top.",
    editorKicker: "A note before you go",
    editorTitle: "If you only have ten minutes",
    editor: [
      "Start with the rolls. Thirteen crore names is the kind of figure that goes numb unless you picture one booth, one queue, and a person told their name is no longer on the list. Congress wants the revision stopped, and it wants the Prime Minister and the chief election commissioner to go. The INDIA bloc sits down today to see if it can say that in a single voice.",
      "If that is too loud before chai, the court was plainer on Tuesday. A cancer drug sold at ten times its price was called carnage. Patients already knew. The matter comes back on 12 October.",
      "Thane is not a metaphor. A Shiv Sena (UBT) leader was shot on Tuesday night and died in hospital. Nagoya is not a metaphor either: the archery team equalled a world record this morning, and Neeru Dhanda won trap gold ten days after a hospital bed. A paper is allowed to hold both.",
      "Do not skip the world section because the word India is in the masthead. Gaza, a sanctions list, a mobilisation law in Beijing, a sentence spoken in Rome. Read one of them before you close the tab.",
      "And if you are only planning the day: rain holds over Kerala, Tamil Nadu and the Northeast. Delhi should be dry. The monsoon deficit is down to 12 percent. Better than last week. Still not the season anyone ordered.",
    ],
    figuresKicker: "On the notebook",
    figuresTitle: "Figures worth keeping",
    figures: [
      ["13 crore", "names Congress wants put back on the rolls"],
      ["16%", "the medicine margin the Supreme Court is pressing for"],
      ["238–234", "India’s world-record score against China in Nagoya"],
      ["8 weeks", "the Nifty’s losing run, the longest since 2020"],
      ["12%", "how far the monsoon is still short of normal"],
      ["₹10,000 cr", "the Inox Clean Energy listing, filed overnight"],
    ],
    cityKicker: "City desk",
    cityTitle: "Where the morning landed",
    cities: [
      ["New Delhi", "The rolls, the court, and a sky that should stay dry.", "sir-rolls"],
      ["Thane", "A party leader shot on Tuesday night. He died in hospital.", "thane-shooting"],
      ["Mumbai", "Eight losing weeks, and a renewables company asking the market for ₹10,000 crore.", "nifty"],
      ["Kerala", "Heavy rain, thunder, and the monsoon still not ready to leave the south.", "wednesday-rain"],
      ["Nagoya", "Archery gold, a world record, and Neeru Dhanda’s 28.", "archery-gold"],
      ["Gaza City", "A commander killed at dawn. The war’s numbers are in the piece.", "gaza-strike"],
    ],
    reported: "Reported by",
    original: "Open the original",
    related: "Beside it on the desk",
    indiaDesk: "India desk",
    worldDesk: "World wire",
    justIn: "Just in",
    minute: "min read",
    footerBlurb:
      "The paper is set from publisher wires and changes with the date. Each brief is a short reading of someone else’s report, and links out to it.",
    footerHint: "Press / to search. Esc closes a piece. The arrow keys move through what you have open.",
    madeBy: "Made by",
    edition: "Edition",
    live: "Live",
    latest: "Latest",
    today: "Today",
    yesterday: "Yesterday",
    setting: "The wires",
    settingTitle: "Setting today’s paper.",
    emptyDay: "Nothing on the wire for this date yet. Try today, or the day before.",
    savedWire: "The live wire did not answer, so this is the saved edition from 30 September 2026.",
    liveWire: "Taken off the wires",
    editorTitleLive: "What leads the paper",
    editorTitlePast: "What led that day",
    letterClose: "The date along the top changes the paper. Leave it on today and it will move when the day does. Headlines refresh through the sitting.",
    figIndia: "pieces filed from India",
    figWorld: "pieces from the rest of the world",
    figPlaces: "places named on this page",
  },
  hi: {
    tagline: "भारत के लिए सुबह का अख़बार, और दुनिया उसी पन्ने पर।",
    search: "शहर, विषय या नाम",
    searchGo: "खोजें",
    all: "पूरा अंक",
    india: "भारत",
    world: "दुनिया",
    region: "क्षेत्र",
    topic: "विषय",
    place: "जगह",
    everywhere: "हर क्षेत्र",
    allTopics: "हर विषय",
    allPlaces: "हर जगह",
    read: "पूरी ख़बर पढ़ें",
    close: "बंद करें",
    prev: "पिछली",
    next: "अगली",
    clear: "फ़िल्टर हटाएँ",
    matchOne: "ख़बर इस चुनाव पर",
    matchMany: "ख़बरें इस चुनाव पर",
    nothingKicker: "खाली स्तंभ",
    nothingTitle: "इस शीर्षक के नीचे कुछ नहीं मिला।",
    nothingBody: "कोई और शहर चुनें, या फ़िल्टर हटा दें। बाक़ी अख़बार यहीं है।",
    onlyPiece: "इस चुनाव में बस यही एक ख़बर है।",
    worldKicker: "देश से बाहर",
    worldTitle: "भारत से परे सबसे बड़ी ख़बरें",
    worldNote: "गाज़ा, तेहरान की आपूर्ति, बीजिंग, रोम में कही गई एक बात, और एक नया नाम।",
    indiaKicker: "देश",
    indiaTitle: "सुबह का बाक़ी भारत",
    indiaNote: "अदालत, ठाणे, नागोया का सोना, थका बाज़ार, और आख़िरी बारिश।",
    resultsKicker: "आपका चुनाव",
    resultsTitle: "इसी शीर्षक की और ख़बरें",
    resultsNote: "ऊपर वाली ख़बर हम पहले पन्ने पर रखते।",
    editorKicker: "जाने से पहले",
    editorTitle: "अगर आपके पास सिर्फ़ दस मिनट हैं",
    editor: [
      "मतदाता सूची से शुरू करें। तेरह करोड़ नाम ऐसा आँकड़ा है जो सुन्न कर देता है, जब तक आप एक बूथ, एक कतार, और उस इंसान को न सोचें जिसे बताया गया कि उसका नाम अब सूची में नहीं है। कांग्रेस चाहती है कि यह संशोधन रुके, और प्रधानमंत्री तथा मुख्य चुनाव आयुक्त दोनों हटें। इंडिया गठबंधन आज बैठ रहा है, यह देखने के लिए कि यह बात एक स्वर में कही जा सकती है या नहीं।",
      "अगर यह चाय से पहले बहुत शोर है, तो मंगलवार को अदालत साफ़ थी। कैंसर की दवा दस गुना दाम पर बिक रही थी। पीठ ने इसे क़त्लेआम कहा। मरीज़ यह पहले से जानते थे। मामला 12 अक्टूबर को लौटेगा।",
      "ठाणे कोई रूपक नहीं है। शिवसेना (यूबीटी) के एक नेता को मंगलवार रात गोलियाँ लगीं और अस्पताल में उनकी मृत्यु हो गई। नागोया भी रूपक नहीं है। तीरंदाज़ी की टीम ने आज सुबह विश्व रिकॉर्ड के बराबर स्कोर किया, और नीरू ढांडा ने अस्पताल से निकलने के दस दिन बाद ट्रैप में सोना जीता। एक अख़बार में ये दोनों बातें एक साथ रह सकती हैं।",
      "विश्व वाला हिस्सा इसलिए न छोड़ें कि मस्तूल पर भारत लिखा है। गाज़ा, प्रतिबंधों की एक सूची, बीजिंग का सैन्य कानून, रोम में कही गई एक बात। टैब बंद करने से पहले इनमें से एक पढ़ लें।",
      "और अगर आप सिर्फ़ दिन की योजना बना रहे हैं: केरल, तमिलनाडु और पूर्वोत्तर में बारिश रुकी हुई है। दिल्ली सूखी रहनी चाहिए। मानसून की कमी 12 प्रतिशत पर आ गई है। पिछले हफ़्ते से बेहतर। फिर भी वह मौसम नहीं जो किसी ने माँगा था।",
    ],
    figuresKicker: "कापी पर",
    figuresTitle: "जो आँकड़े रह जाएँ",
    figures: [
      ["13 करोड़", "नाम, जिन्हें कांग्रेस सूची में वापस चाहती है"],
      ["16%", "दवा पर वह मार्जिन, जिसकी बात सुप्रीम कोर्ट कर रहा है"],
      ["238–234", "नागोया में चीन के ख़िलाफ़ भारत का विश्व रिकॉर्ड स्कोर"],
      ["8 हफ़्ते", "निफ्टी की गिरावट, 2020 के बाद सबसे लंबी"],
      ["12%", "मानसून अभी भी सामान्य से इतना पीछे"],
      ["₹10,000 करोड़", "इनॉक्स क्लीन एनर्जी की लिस्टिंग, रात को दाखिल"],
    ],
    cityKicker: "शहर डेस्क",
    cityTitle: "सुबह कहाँ उतरी",
    cities: [
      ["नई दिल्ली", "सूचियाँ, अदालत, और आसमान जो सूखा रहना चाहिए।", "sir-rolls"],
      ["ठाणे", "मंगलवार रात एक पार्टी नेता को गोलियाँ लगीं। अस्पताल में मृत्यु हुई।", "thane-shooting"],
      ["मुंबई", "आठ हारते हफ़्ते, और एक कंपनी बाज़ार से ₹10,000 करोड़ माँग रही है।", "nifty"],
      ["केरल", "भारी बारिश, गरज, और मानसून जो दक्षिण छोड़ने को तैयार नहीं।", "wednesday-rain"],
      ["नागोया", "तीरंदाज़ी का सोना, एक विश्व रिकॉर्ड, और नीरू ढांडा के 28।", "archery-gold"],
      ["गाज़ा शहर", "भोर में एक कमांडर मारा गया। युद्ध के आँकड़े ख़बर में हैं।", "gaza-strike"],
    ],
    reported: "रिपोर्ट",
    original: "मूल ख़बर खोलें",
    related: "डेस्क पर इसके बगल",
    indiaDesk: "भारत डेस्क",
    worldDesk: "विश्व तार",
    justIn: "अभी",
    minute: "मिनट",
    footerBlurb:
      "अख़बार प्रकाशकों के तार से जमती है और तारीख़ के साथ बदलता है। हर ख़बर किसी और की रिपोर्ट का छोटा रूप है, और उसी तक जाती है।",
    footerHint: "खोज के लिए / दबाएँ। Esc ख़बर बंद करता है। तीर वाली कुंजियाँ खुली ख़बरें बदलती हैं।",
    madeBy: "बनाने वाले",
    edition: "अंक",
    live: "लाइव",
    latest: "ताज़ा",
    today: "आज",
    yesterday: "कल",
    setting: "तार",
    settingTitle: "आज का अख़बार जम रहा है।",
    emptyDay: "इस तारीख़ पर तार अभी खाली है। आज या पिछला दिन देखें।",
    savedWire: "लाइव तार नहीं खुला, इसलिए यह 30 सितंबर 2026 का सहेजा अंक है।",
    liveWire: "तार से लिया गया",
    editorTitleLive: "पन्ने पर क्या आगे है",
    editorTitlePast: "उस दिन आगे क्या था",
    letterClose: "ऊपर की तारीख़ अख़बार बदलती है। उसे आज पर छोड़ दें, तो दिन बदलते ही पन्ना आगे बढ़ेगा। सुर्खियाँ बैठक के दौरान ताज़ा होती रहती हैं।",
    figIndia: "भारत से आई ख़बरें",
    figWorld: "बाक़ी दुनिया से आई ख़बरें",
    figPlaces: "इस पन्ने पर जगहों के नाम",
  },
};

export const LABELS = {
  en: {
    topics: {
      Politics: "Politics",
      Courts: "Courts",
      Crime: "Crime",
      Sport: "Sport",
      Markets: "Markets",
      Climate: "Climate",
      Aviation: "Aviation",
      Technology: "Technology",
      Conflict: "Conflict",
    },
    regions: {
      "North India": "North India",
      "West India": "West India",
      "South India": "South India",
      "Northeast India": "Northeast India",
      "East Asia": "East Asia",
      "Middle East": "Middle East",
      "North America": "North America",
      Europe: "Europe",
      "East India": "East India",
      "Across India": "Across India",
      "South Asia": "South Asia",
      World: "World",
    },
    places: {
      "New Delhi": "New Delhi",
      Mumbai: "Mumbai",
      Thane: "Thane",
      Kerala: "Kerala",
      Assam: "Assam",
      Nagoya: "Nagoya",
      Beijing: "Beijing",
      Pyongyang: "Pyongyang",
      "Gaza City": "Gaza City",
      Rome: "Rome",
      Washington: "Washington",
      India: "India",
      World: "World",
      Bengaluru: "Bengaluru",
      Chennai: "Chennai",
      Hyderabad: "Hyderabad",
      Kolkata: "Kolkata",
      Lucknow: "Lucknow",
      Jaipur: "Jaipur",
      Srinagar: "Srinagar",
      Patna: "Patna",
      Ahmedabad: "Ahmedabad",
      Tokyo: "Tokyo",
      Tehran: "Tehran",
      Islamabad: "Islamabad",
      London: "London",
      Kyiv: "Kyiv",
      Moscow: "Moscow",
    },
    signals: {
      Breaking: "Breaking",
      Developing: "Developing",
      Result: "Result",
      Desk: "Desk",
    },
  },
  hi: {
    topics: {
      Politics: "राजनीति",
      Courts: "अदालत",
      Crime: "अपराध",
      Sport: "खेल",
      Markets: "बाज़ार",
      Climate: "मौसम",
      Aviation: "उड़ान",
      Technology: "तकनीक",
      Conflict: "संघर्ष",
    },
    regions: {
      "North India": "उत्तर भारत",
      "West India": "पश्चिम भारत",
      "South India": "दक्षिण भारत",
      "Northeast India": "पूर्वोत्तर",
      "East Asia": "पूर्व एशिया",
      "Middle East": "पश्चिम एशिया",
      "North America": "उत्तरी अमेरिका",
      Europe: "यूरोप",
      "East India": "पूर्व भारत",
      "Across India": "पूरे भारत",
      "South Asia": "दक्षिण एशिया",
      World: "दुनिया",
    },
    places: {
      "New Delhi": "नई दिल्ली",
      Mumbai: "मुंबई",
      Thane: "ठाणे",
      Kerala: "केरल",
      Assam: "असम",
      Nagoya: "नागोया",
      Beijing: "बीजिंग",
      Pyongyang: "प्योंगयांग",
      "Gaza City": "गाज़ा शहर",
      Rome: "रोम",
      Washington: "वॉशिंगटन",
      India: "भारत",
      World: "दुनिया",
      Bengaluru: "बेंगलुरु",
      Chennai: "चेन्नई",
      Hyderabad: "हैदराबाद",
      Kolkata: "कोलकाता",
      Lucknow: "लखनऊ",
      Jaipur: "जयपुर",
      Srinagar: "श्रीनगर",
      Patna: "पटना",
      Ahmedabad: "अहमदाबाद",
      Tokyo: "टोक्यो",
      Tehran: "तेहरान",
      Islamabad: "इस्लामाबाद",
      London: "लंदन",
      Kyiv: "कीव",
      Moscow: "मॉस्को",
    },
    signals: {
      Breaking: "ब्रेकिंग",
      Developing: "जारी",
      Result: "नतीजा",
      Desk: "डेस्क",
    },
  },
};
