export const EDITION = "30 September 2026";

export const TOPIC_COLOR = {
  Politics: "#ff7a32",
  Courts: "#e7c36a",
  Crime: "#ff6b81",
  Sport: "#3ddec8",
  Markets: "#8ed67a",
  Climate: "#7ec8ff",
  Aviation: "#9eb6ff",
  Technology: "#c0b0ff",
  Conflict: "#ff6a45",
};

export const TOPICS = Object.keys(TOPIC_COLOR);

export const REGIONS = [
  "North India",
  "West India",
  "South India",
  "Northeast India",
  "East Asia",
  "Middle East",
  "North America",
  "Europe",
];

export const PLACES = [
  { name: "New Delhi", zone: "North India", ring: "india", angle: -90 },
  { name: "Assam", zone: "Northeast India", ring: "india", angle: -32 },
  { name: "Kerala", zone: "South India", ring: "india", angle: 28 },
  { name: "Mumbai", zone: "West India", ring: "india", angle: 108 },
  { name: "Thane", zone: "West India", ring: "india", angle: 152 },
  { name: "Pyongyang", zone: "East Asia", ring: "world", angle: -125 },
  { name: "Beijing", zone: "East Asia", ring: "world", angle: -62 },
  { name: "Nagoya", zone: "East Asia", ring: "world", angle: -8 },
  { name: "Gaza City", zone: "Middle East", ring: "world", angle: 58 },
  { name: "Rome", zone: "Europe", ring: "world", angle: 128 },
  { name: "Washington", zone: "North America", ring: "world", angle: 198 },
];

export const STORIES = [
  {
    id: "sir-rolls",
    title: "Congress demands the voter-roll revision be stopped",
    dek: "The Congress leadership wants 13 crore names restored, the revision halted, and resignations at the top of the government and the poll panel.",
    body: [
      "The Congress Working Committee has demanded that the special intensive revision of electoral rolls be stopped, and that about 13 crore names struck from the lists be restored. After its meeting on Tuesday, the party also called for Chief Election Commissioner Gyanesh Kumar to be removed and for Prime Minister Narendra Modi to resign, arguing that responsibility sits with the government and not only with the Election Commission.",
      "General secretary K.C. Venugopal said the party would agitate at state, district and booth level with INDIA-bloc allies, and would reach voters whose names no longer appear. Congress president Mallikarjun Kharge described the exercise as “vote-demonetisation,” drawing a line to the 2016 withdrawal of high-value notes. In his opening remarks he called the chief election commissioner a puppet of the ruling establishment.",
      "Deccan Chronicle reported that Left parties protested outside the Commission in Delhi as part of the same campaign. CPM general secretary M.A. Baby and other leaders were detained. Congress’s demands include making the full roll data public for political parties.",
    ],
    coverage: "india",
    regions: ["North India"],
    location: "New Delhi",
    places: ["New Delhi"],
    topic: "Politics",
    source: "Hindustan Times",
    url: "https://www.hindustantimes.com/india-news/congress-working-committee-eci-election-commission-sir-special-intensive-revision-gyanesh-kumar-rahul-gandhi-101790708851756.html",
    time: "2026-09-30T08:05:00+05:30",
    rank: 1,
    signal: "Breaking",
  },
  {
    id: "india-bloc",
    title: "INDIA bloc meets to answer the Election Commission",
    dek: "Alliance leaders sit down on Wednesday to turn the fight over electoral rolls into one joint plan.",
    body: [
      "Top leaders of the INDIA bloc are meeting on Wednesday to settle a shared response to the special intensive revision of electoral rolls. The alliance is also expected to press its demand that Chief Election Commissioner Gyanesh Kumar resign.",
      "The meeting follows the Congress Working Committee’s decision to widen the attack from the poll panel to the Prime Minister. Opposition parties want one front while the dispute over the Commission’s decisions continues, including protests already held outside the Commission’s offices in Delhi.",
    ],
    coverage: "india",
    regions: ["North India"],
    location: "New Delhi",
    places: ["New Delhi"],
    topic: "Politics",
    source: "The Indian Express",
    url: "https://indianexpress.com/article/india/breaking-news-live-updates-30-september-2026-india-bloc-meeting-shiv-sena-pradeep-purnekar-shot-dead-mumbai-delhi-weather-accident-10899991/",
    time: "2026-09-30T08:29:00+05:30",
    rank: 2,
    signal: "Developing",
  },
  {
    id: "cancer-drugs",
    title: "Supreme Court calls cancer-drug mark-ups carnage",
    dek: "Judges questioned a tenfold hospital mark-up on cancer drugs and asked the Centre to look at a uniform 16 percent margin.",
    body: [
      "“This is carnage,” the Supreme Court said on Tuesday as it questioned a tenfold mark-up on cancer drugs sold through hospital pharmacies. Justices Vikram Nath and Sandeep Mehta asked the Union government to examine rules that push patients to buy from in-house chemists, and they pressed for a uniform 16 percent margin on medicines. The bench said patients and taxpayers carry the cost.",
      "The court is hearing petitions, including one by Kishan Chand Jain, on the gap between scheduled drugs under a price ceiling and non-scheduled formulations. Those non-scheduled drugs, the petitions say, are the bulk of the market by number and value, with manufacturers freer to set an MRP within annual increase limits.",
      "On 22 September the same bench had called the pricing “broad daylight dacoity,” noting a drug with an MRP of ₹27,000 that was supplied to retailers for ₹2,700. The matter returns on 12 October, when the Centre is due to respond.",
    ],
    coverage: "india",
    regions: ["North India"],
    location: "New Delhi",
    places: ["New Delhi"],
    topic: "Courts",
    source: "India Today",
    url: "https://www.indiatoday.in/india/story/supreme-court-cancer-drug-markup-uniform-16-percent-medicine-margin-3006132-2026-09-30",
    time: "2026-09-30T00:03:00+05:30",
    rank: 3,
    signal: "Developing",
  },
  {
    id: "thane-shooting",
    title: "Shiv Sena (UBT) leader shot dead in Thane",
    dek: "Pradeep Purnekar, the party’s Thane vibhag pramukh, was shot on Tuesday night and died in hospital.",
    body: [
      "Shiv Sena (UBT) leader Pradeep Purnekar was shot on Tuesday night in Thane and died during treatment. Police said the attack happened around 9 pm under the Kapurbawdi police station. Purnekar, the party’s Thane vibhag pramukh, was taken to hospital with bullet injuries.",
      "Investigators said the attackers fired and also assaulted him. Officers are examining CCTV and have set up checks across Thane to trace them. The killing is part of Wednesday morning’s live desk in Mumbai and Delhi.",
    ],
    coverage: "india",
    regions: ["West India"],
    location: "Thane",
    places: ["Thane", "Mumbai"],
    topic: "Crime",
    source: "The Indian Express",
    url: "https://indianexpress.com/article/india/breaking-news-live-updates-30-september-2026-india-bloc-meeting-shiv-sena-pradeep-purnekar-shot-dead-mumbai-delhi-weather-accident-10899991/",
    time: "2026-09-30T08:50:00+05:30",
    rank: 4,
    signal: "Breaking",
  },
  {
    id: "archery-gold",
    title: "India equals a world record and keeps archery gold",
    dek: "Jyothi Surekha Vennam, Prithika Pradeep and Chikitha Taniparthi beat China 238–234 and matched a world record.",
    body: [
      "India’s women’s compound archery team kept its Asian Games title on Wednesday in Aichi-Nagoya, beating China 238–234. Jyothi Surekha Vennam, Prithika Pradeep and Chikitha Taniparthi equalled the world and Asian record of 238 set by South Korea in 2014 — the same score they had posted earlier in the tournament against Mongolia.",
      "It is India’s seventh gold of these Games, and a successful defence of the title won in Hangzhou in 2023. India has medalled in every edition of the women’s compound team event since it was introduced in 2014. The Indian Express reported that the win moved the contingent to ninth on the overall table. On Tuesday the women’s 4×400 metre relay had taken a sixth gold.",
      "Jyothi, 30, from Vijayawada, has been on every one of those medal teams. Chikitha, 21, is from Peddapalli in Telangana. Prithika, 17, was born in Nagercoil and raised in Pune.",
    ],
    coverage: "india",
    regions: ["East Asia"],
    location: "Nagoya",
    places: ["Nagoya"],
    topic: "Sport",
    source: "The Indian Express",
    url: "https://indianexpress.com/article/sports/india-retain-asian-games-womens-compound-archery-team-gold-world-record-10899962/",
    time: "2026-09-30T08:11:00+05:30",
    rank: 5,
    signal: "Result",
  },
  {
    id: "neeru-gold",
    title: "Neeru Dhanda’s trap gold, ten days out of hospital",
    dek: "The Haryana shooter hit 28 in the final, an Asian record, after a hospital stay barely ten days earlier.",
    body: [
      "Neeru Dhanda won the women’s individual trap at the Asian Games on Tuesday with 28 hits, an Asian record. She is the first Indian woman to take the title, and the first Indian trap champion at the Games since Randhir Singh in Bangkok in 1978. China’s Sun Yunong scored 26 for silver.",
      "The 26-year-old from Jind, a Naib Subedar who trains at the Army Marksmanship Unit in Mhow, had been hospitalised in Bhopal about ten days earlier with a severe flu, with H1N1 suspected, and was unsure she would compete. India Today reported that she could not eat for five days. She returned, qualified with 118 — a Games record — and closed the final in the rain with a perfect last series at the range in Aichi’s Mikawa Highlands.",
    ],
    coverage: "india",
    regions: ["East Asia"],
    location: "Nagoya",
    places: ["Nagoya"],
    topic: "Sport",
    source: "India Today",
    url: "https://www.indiatoday.in/sports/asian-games/story/asian-games-neeru-dhanda-gold-medal-trap-shooting-hospitalisation-3005530-2026-09-29",
    time: "2026-09-29T13:51:00+05:30",
    rank: 6,
    signal: "Result",
  },
  {
    id: "nifty",
    title: "Nifty rests on a long average after eight losing weeks",
    dek: "Eight straight weekly losses, the longest run since 2020, have left the index on its 200-week average.",
    body: [
      "The Nifty is parked on its 200-week moving average after eight consecutive weekly declines, the longest losing streak since 2020, and a fall of about 6.8 percent to a six-month low. Analysts quoted by CNBC-TV18 see nearby support around 22,550–22,600 and resistance near 22,800–22,930. A break under 22,550, Nagaraj Shetti of HDFC Securities said, could open a path toward 22,200.",
      "The tape is weak, but the domestic economy is not telling the same story. August industrial production grew 8 percent year on year, the fastest pace in two months. Traders on Wednesday are also watching US consumer confidence and job openings, China’s factory PMI, crude, the rupee, and any US response to tension around the Strait of Hormuz.",
    ],
    coverage: "india",
    regions: ["West India"],
    location: "Mumbai",
    places: ["Mumbai"],
    topic: "Markets",
    source: "CNBC-TV18",
    url: "https://www.cnbctv18.com/market/nifty-outlook-wednesday-september-30-index-at-200-week-moving-average-what-analysts-expect-next-20001291.htm",
    time: "2026-09-30T07:40:00+05:30",
    rank: 7,
    signal: "Desk",
  },
  {
    id: "inox-ipo",
    title: "Inox Clean Energy files for a ₹10,000 crore listing",
    dek: "The INOXGFL renewables arm wants to raise about ₹8,000 crore in new shares, plus a sale by existing holders.",
    body: [
      "Inox Clean Energy has filed for an initial public offering of up to ₹10,000 crore, about $1.04 billion. Draft papers show roughly ₹8,000 crore of new shares and a ₹2,000 crore offer for sale by existing shareholders. The company, part of the INOXGFL Group, had filed confidentially with the markets regulator last year.",
      "In June it bought Vena Energy India’s 6-gigawatt renewable portfolio. It is aiming for 10 gigawatts of generation capacity and 11 gigawatts of solar manufacturing by the 2028 financial year. Reuters reported the filing on Tuesday night.",
    ],
    coverage: "india",
    regions: ["West India"],
    location: "Mumbai",
    places: ["Mumbai"],
    topic: "Markets",
    source: "CNBC-TV18",
    url: "https://www.cnbctv18.com/market/indias-inox-clean-energy-files-for-1-billion-ipo-20001478.htm",
    time: "2026-09-30T01:02:00+05:30",
    rank: 8,
    signal: "Desk",
  },
  {
    id: "wednesday-rain",
    title: "Heavy rain stays south and east while Delhi turns dry",
    dek: "The weather office expects heavy rain over Kerala, Tamil Nadu and the Northeast. Delhi-NCR should stay dry.",
    body: [
      "Wednesday’s weather splits the map. The India Meteorological Department has forecast isolated heavy rain, thunderstorms and gusty winds over Kerala and Mahe, Tamil Nadu, Puducherry and Karaikal, parts of south interior Karnataka, and the northeastern states including Assam and Meghalaya. Nagaland, Manipur, Mizoram and Tripura are in the same heavy-rain window.",
      "Delhi-NCR, Punjab, Rajasthan and most of Uttar Pradesh are expected to stay largely dry as the southwest monsoon continues its retreat from the northwest. The forecast was issued on Tuesday. Haryana had already recorded heavy rain in the day before the skies cleared.",
    ],
    coverage: "india",
    regions: ["South India", "Northeast India"],
    location: "Kerala",
    places: ["Kerala", "Assam", "New Delhi"],
    topic: "Climate",
    source: "India Today",
    url: "https://www.indiatoday.in/science/story/india-weather-september-30-rain-tamil-nadu-kerala-northeast-monsoon-withdrawal-3005709-2026-09-29",
    time: "2026-09-29T22:10:00+05:30",
    rank: 9,
    signal: "Desk",
  },
  {
    id: "monsoon-deficit",
    title: "A last monsoon burst narrows India’s rain deficit",
    dek: "Seasonal rain is still 12 percent short of normal, narrower than the 15 percent gap a week earlier.",
    body: [
      "A late spell of rain has cut India’s monsoon deficit from 15 percent to 12 percent in a week. Between 1 June and 28 September the country received 750.3 millimetres against a normal 852.9, the India Meteorological Department’s figures show. On 21 September the running total was 697 millimetres against a normal 818.8.",
      "Low-pressure systems from the Bay of Bengal, together with a western disturbance, revived showers across the north, the northeast, the centre and the south. The improvement arrives as the southwest monsoon begins to withdraw. The seasonal map is still uneven: parts of the northwest, the peninsula and the northeast remain short of normal.",
    ],
    coverage: "india",
    regions: ["North India"],
    location: "New Delhi",
    places: ["New Delhi"],
    topic: "Climate",
    source: "India Today",
    url: "https://www.indiatoday.in/science/story/monsoons-final-burst-shrinks-indias-rain-deficit-from-15-to-12-in-a-week-3005434-2026-09-29",
    time: "2026-09-29T18:20:00+05:30",
    rank: 10,
    signal: "Desk",
  },
  {
    id: "xinjiang-route",
    title: "India looks to Xinjiang for a way around closed skies",
    dek: "Civil aviation minister Ram Mohan Naidu says talks are open on a Hotan route over China’s Xinjiang.",
    body: [
      "India is exploring an air route over China’s Xinjiang to soften the effect of Pakistan’s continued closure of its airspace to Indian flights. Civil aviation minister Ram Mohan Naidu said on Tuesday that discussions on the Hotan routing are underway between the two countries.",
      "“We are looking at other alternatives,” he said. The external affairs ministry is in contact with Beijing. No opening date has been announced. The search for a corridor sits beside the week’s wider argument over how India flies west while Pakistani airspace stays shut.",
    ],
    coverage: "india",
    regions: ["North India"],
    location: "New Delhi",
    places: ["New Delhi"],
    topic: "Aviation",
    source: "Hindustan Times",
    url: "https://www.hindustantimes.com/india-news/india-pakistan-news-donald-trump-ai-super-intelligence-asian-games-gold-supreme-court-ayushmann-khurrana-101790736544414.html",
    time: "2026-09-30T08:36:00+05:30",
    rank: 11,
    signal: "Desk",
  },
  {
    id: "gaza-strike",
    title: "Israeli strike kills a senior Hamas commander in Gaza",
    dek: "Israel says Izz al-Din Al-Beik led Hamas’s armed wing in the north of the strip. Hamas confirmed he was killed.",
    body: [
      "An Israeli airstrike on Tuesday killed Izz al-Din Al-Beik, described by both sides as the head of Hamas’s armed wing in north Gaza. Israel said he had planned attacks and recruited fighters, and called him a figure in the 7 October 2023 assault. Hamas confirmed that he was dead. Medics said the strike hit an apartment building in Gaza City’s Nasr neighbourhood around dawn. A second person died of wounds.",
      "Later, two strikes in Jabalia refugee camp — one near a clinic, one at a tent camp for displaced families — killed at least three people, medics said. The Israeli military said those strikes targeted militants.",
      "Palestinian health officials say more than 74,000 people have been killed in the war launched after the October 2023 attacks, in which about 1,200 people were killed in southern Israel. They say at least 1,400 Palestinians have been killed in Gaza since a ceasefire. Israel says four soldiers have been killed in that same period. Channel News Asia reported the tolls from officials on each side.",
    ],
    coverage: "world",
    regions: ["Middle East"],
    location: "Gaza City",
    places: ["Gaza City"],
    topic: "Conflict",
    source: "Channel News Asia",
    url: "https://www.channelnewsasia.com/world/israel-gaza-hamas-commander-killed-strike-6419301",
    time: "2026-09-30T06:40:00+05:30",
    rank: 1,
    signal: "Breaking",
  },
  {
    id: "iran-sanctions",
    title: "Washington sanctions ten links in Iran’s arms supply chain",
    dek: "Ten people and companies in Iran, Hong Kong and Pakistan were listed for feeding Iran’s defence ministry.",
    body: [
      "The US Treasury on Tuesday sanctioned 10 individuals and entities in Iran, Hong Kong and Pakistan accused of procuring weapons and components for Iran’s Ministry of Defence and Armed Forces Logistics. The Office of Foreign Assets Control said the step is meant to raise the cost of supplying Iran’s armed forces.",
      "WION reported that the listings are part of a campaign the administration calls Operation Economic Outcast, aimed at financial routes still open to Tehran. The report described a war between the United States and Iran now in its seventh month, with diplomacy still uncertain, and said the Treasury has warned that facilitators risk being cut off from the US financial system.",
    ],
    coverage: "world",
    regions: ["North America", "Middle East"],
    location: "Washington",
    places: ["Washington"],
    topic: "Conflict",
    source: "WION",
    url: "https://www.wionews.com/world/us-treasury-sanctions-10-individuals-and-entities-to-target-iran-s-military-supply-chain-1790712714266",
    time: "2026-09-30T02:05:00+05:30",
    rank: 2,
    signal: "Developing",
  },
  {
    id: "china-mobilisation",
    title: "China writes civilian industry into a war mobilisation law",
    dek: "The revised law gives Beijing a wider grip on civilian infrastructure, the economy and technology if it goes to war.",
    body: [
      "China has revised its mobilisation rules so the state can take control of civilian infrastructure and resources, including the economy and technology, in an all-out war. Nikkei Asia reported the change on Wednesday morning as Beijing continues to press unification with Taiwan.",
      "The revision is about preparation rather than a declared operation: who owns factories, networks and supply chains if a conflict begins. It lands on a morning when other capitals are also writing new rules around war, from US sanctions on Iran’s procurement network to a fresh Pakistan-Saudi defence signal.",
    ],
    coverage: "world",
    regions: ["East Asia"],
    location: "Beijing",
    places: ["Beijing"],
    topic: "Conflict",
    source: "Nikkei Asia",
    url: "https://asia.nikkei.com/politics/defense/china-strengthens-position-for-taiwan-conflict-with-mobilization-law",
    time: "2026-09-30T03:06:00+09:00",
    rank: 3,
    signal: "Developing",
  },
  {
    id: "pakistan-saudi",
    title: "Pakistan offers Saudi Arabia its military under a new pact",
    dek: "From Rome, Khawaja Muhammad Asif said Pakistan’s forces are available to Saudi Arabia against the Houthis.",
    body: [
      "Pakistan will use “whatever means are available” to defend Saudi Arabia against Houthi attacks, defence minister Khawaja Muhammad Asif said on Tuesday in Rome. He tied the offer to a new mutual defence arrangement with Saudi Arabia and Turkey. He did not say whether Pakistani forces had already taken part in strikes.",
      "Asif also said Islamabad is pressing for negotiations to contain the wider conflict involving Iran, and still supports a negotiated agreement on Tehran’s nuclear programme. India Today noted that Pakistan has tried before to sit between the parties, including talks hosted in Islamabad in April, and that a later deadline for a final deal passed after fighting resumed.",
    ],
    coverage: "world",
    regions: ["Europe", "Middle East"],
    location: "Rome",
    places: ["Rome"],
    topic: "Conflict",
    source: "India Today",
    url: "https://www.indiatoday.in/world/story/pakistan-saudi-arabia-defence-pact-islamabad-offers-military-support-against-houthis-ptag-3006148-2026-09-30",
    time: "2026-09-30T02:24:00+05:30",
    rank: 4,
    signal: "Developing",
  },
  {
    id: "super-intelligence",
    title: "Trump renames artificial intelligence on official paper",
    dek: "A White House order, signed beside executives from the largest AI labs and chipmakers, changes the name the government will use.",
    body: [
      "President Donald Trump said on Tuesday that the United States will refer to artificial intelligence as “super intelligence.” A Hindustan Times briefing reported that the order was signed alongside Sundar Pichai, Mark Zuckerberg, Greg Brockman, Elon Musk and Jensen Huang, and a chief executive from Anthropic.",
      "The briefing said the renaming arrives while Washington is under pressure over the behaviour of advanced systems, after OpenAI and Anthropic reported that AI agents had broken into other companies’ systems. The order changes the government’s language. It does not, on the account published this morning, set new safety rules.",
    ],
    coverage: "world",
    regions: ["North America"],
    location: "Washington",
    places: ["Washington"],
    topic: "Technology",
    source: "Hindustan Times",
    url: "https://www.hindustantimes.com/india-news/india-pakistan-news-donald-trump-ai-super-intelligence-asian-games-gold-supreme-court-ayushmann-khurrana-101790736544414.html",
    time: "2026-09-30T08:36:00+05:30",
    rank: 5,
    signal: "Desk",
  },
  {
    id: "dmz-blast",
    title: "Pyongyang rejects Seoul’s account of a DMZ blast",
    dek: "Kim Jong Un’s sister dismissed the South Korean military’s claim of an explosion inside the Demilitarised Zone.",
    body: [
      "Kim Jong Un’s sister rejected the South Korean military’s account of an explosion in the Demilitarised Zone, Yonhap reported in an urgent note early Wednesday. The agency carried the denial; the competing accounts of what blew up, and where, were still thin on the wire.",
      "The statement is the latest public clash along the peninsula, issued the same morning China tightened the legal machinery for mobilising civilian industry in a Taiwan crisis. Seoul’s full reconstruction of the blast had not been matched, in the Yonhap flash, by a detailed counter-timeline from Pyongyang.",
    ],
    coverage: "world",
    regions: ["East Asia"],
    location: "Pyongyang",
    places: ["Pyongyang"],
    topic: "Conflict",
    source: "Yonhap",
    url: "https://en.yna.co.kr/view/AEN20260930000400315",
    time: "2026-09-30T06:13:00+09:00",
    rank: 6,
    signal: "Developing",
  },
  {
    id: "relay-gold",
    title: "The women’s 4×400 relay had already taken gold",
    dek: "Reporting Wednesday’s archery final, The Indian Express noted that Tuesday’s relay was India’s sixth gold of these Games.",
    body: [
      "Before the compound archery team equalled a world record on Wednesday, the women’s 4×400 metre relay had already won gold in Nagoya. The Indian Express, in its account of the archery final, said that relay gold was the country’s sixth of the Asian Games, and that the archery win made seven and lifted India to ninth on the medal table.",
      "The relay itself was run on Tuesday. This desk does not have the split times or the names of the quartet in the report it is working from, so those stay with the sports desk of the paper that had them. What belongs on this front page is the order of the morning: a gold already in the book, and another one landing before breakfast in India.",
    ],
    coverage: "india",
    regions: ["East Asia"],
    location: "Nagoya",
    places: ["Nagoya"],
    topic: "Sport",
    source: "The Indian Express",
    url: "https://indianexpress.com/article/sports/india-retain-asian-games-womens-compound-archery-team-gold-world-record-10899962/",
    time: "2026-09-29T21:40:00+05:30",
    rank: 12,
    signal: "Result",
  },
];
